fix/interactive: terminal resize while waiting user input caused crash
If user's terminal got resized in `interactive` mode he/she would get a panic.

```
thread 'main' panicked at 'internal error: entered unreachable code: Unexpected return when dealing with user input', src/action/interactive.rs:320:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Signed-off-by: Maxim Zhiburt <zhiburt@gmail.com>